language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '3.4'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.5'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.6'
    env: BUILD_SDIST=true
  - os: linux
    sudo: false
    python: pypy3
  - os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.12
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.5.2
before_install:
  - chmod +x .travis/install.sh
install:
  - "./.travis/install.sh"
script:
  - "./.travis/run.sh"
