os: linux
sudo: false
language: python

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

matrix:
  include:
  - python: '3.5'
  - python: '3.6'
  - python: '3.7'
  - python: pypy3
  allow_failures:
    - python: pypy3
  fast_finish: true

before_install:
  - pip install codecov

install:
  - python scripts/install  

script:
   - python scripts/run-tests

after_success:
  - rm tests/coverage.xml && mv tests/.coverage ./ && codecov
