language: python
matrix:
  include:
  - python: '3.7'
    sudo: false
  - python: '3.8'
    sudo: false
  - python: pypy3
  allow_failures:
    - python: pypy3

cache: pip
before_install:
  - pip install poetry nox

install:
  - poetry install

script: nox
