language: python

matrix:
  include:
  - python: '3.5'
    dist: xenial
    sudo: false
  - python: '3.6'
    dist: xenial
    sudo: false
  - python: '3.7'
    dist: xenial
    sudo: true
  - python: pypy3
  allow_failures:
    - python: pypy3
  fast_finish: true

cache: pip
before_install:
  - pip install codecov

install:
  - python scripts/install  

script:
   - python scripts/run-tests

after_success:
  - rm tests/coverage.xml && mv tests/.coverage ./ && codecov
