#!/usr/bin/env python
import os
import sys
from subprocess import check_call
import shutil

_dname = os.path.dirname

REPO_ROOT = _dname(_dname(_dname(os.path.abspath(__file__))))
os.chdir(REPO_ROOT)

def run(command):
    return check_call(command, shell=True)

try:
    # Has the form "major.minor"
    python_version = os.environ['PYTHON_VERSION']
except KeyError:
    python_version = '.'.join([str(i) for i in sys.version_info[:2]])

run('pip install coverage')
if os.path.isdir('dist') and os.listdir('dist'):
    shutil.rmtree('dist')

REQUIRE_SPEEDUPS=1 python setup.py build_ext -i
run('python -m compileall -f .')
run('coverage run --omit="*/tests/*" -m unittest discover')
run('python setup.py sdist')

#wheel_dist = os.listdir('dist')[0]
#run('pip install %s' % (os.path.join('dist', wheel_dist)))
