name: Dependabot

on:
  pull_request:
    branches:
      - master

jobs:
  automerge:
    name: Merge pull request
    runs-on: ubuntu-latest
    if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
    steps:
      - name: Merge
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
