name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Publish the release notes
        uses: release-drafter/release-drafter@v5.11.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
