name: Tests
on: [push, pull_request]
jobs:
  tests:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.7", "3.8"]
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-python@v1.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip install --constraint=.github/workflows/constraints.txt nox poetry
      - run: nox --force-color
